module.exports = {
  rules: {
    'body-leading-blank': [1, 'always', 100],
    'footer-leading-blank': [1, 'always', 100],
    'body-max-line-length': [2, 'always', 100],
    'footer-max-line-length': [2, 'always', 100],
    'header-case': [2, 'never', ['snake-case', 'kebab-case', 'upper-case']],
    'header-max-length': [2, 'always', 140],
    'scope-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'improvement',
        'enhancement',
        'revert',
        'style',
        'test',
        'release',
        'deps',
      ],
    ],
  },
};